# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant::configure("2") do |config|

  config.hostmanager.enabled = false
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.provision :hostmanager

  config.vm.define :johan do |johan_config|
    johan_config.vm.box = "johan"
    johan_config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box"
    johan_config.vm.network :private_network, ip: "192.168.127.207"
    johan_config.vm.network :public_network, bridge: "em1"
    johan_config.vm.hostname = "johan.koewacht.net"
    johan_config.hostmanager.aliases = %w(johan)
    johan_config.vm.synced_folder "puppet", "/data/puppet", id: "puppet-mod-root", disabled: false
    johan_config.vm.provider :virtualbox do |vb|
      vb.customize [ 'modifyvm', :id, '--name', "johan-#{Time.now.to_i}", "--memory", "1024" ]
    end
  end


  config.vm.define :activeMQ do |activeMQ_config|
    activeMQ_config.vm.box = "activeMQ"
    activeMQ_config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box"
    activeMQ_config.vm.network :private_network, ip: "192.168.127.206"
    activeMQ_config.vm.network :public_network, bridge: "em1"
    activeMQ_config.vm.hostname = "activeMQ.koewacht.net"
    activeMQ_config.hostmanager.aliases = %w(activeMQ)
    activeMQ_config.vm.synced_folder "puppet", "/data/puppet", id: "puppet-mod-root", disabled: false
    activeMQ_config.vm.provider :virtualbox do |vb|
      vb.customize [ 'modifyvm', :id, '--name', "activeMQ-#{Time.now.to_i}", "--memory", "1024" ]
    end
  end
end
